/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Controller.UserDAO;
import Models.User;
import java.sql.SQLException;
import javax.swing.ButtonGroup;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author nguye
 */
public class FrmDangKi extends javax.swing.JFrame {

    /**
     * Creates new form FrmDangKi
     */
    public FrmDangKi() {
        initComponents();
        ButtonGroup group = new ButtonGroup();
        group.add(radNam);
        group.add(radNu);
        lblErrorTK.setText("");
        lblErrorMK.setText("");
        lblErrorNLMK.setText("");
        lblErrorEmail.setText("");
        lblErrorSDT.setText("");
        lblErrorNS.setText("");
        lblErrorGT.setText("");
        lblErrorHT.setText("");
        lblErrorDC.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnDanhKi = new javax.swing.JButton();
        txtTenTaiKhoan = new javax.swing.JTextField();
        txtHoTen = new javax.swing.JTextField();
        txtNgay = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtSoDT = new javax.swing.JTextField();
        txtPw = new javax.swing.JPasswordField();
        txtNhapLaiPw = new javax.swing.JPasswordField();
        radNam = new javax.swing.JRadioButton();
        radNu = new javax.swing.JRadioButton();
        txtThang = new javax.swing.JTextField();
        txtNam = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblErrorTK = new javax.swing.JLabel();
        lblErrorMK = new javax.swing.JLabel();
        lblErrorNLMK = new javax.swing.JLabel();
        lblErrorHT = new javax.swing.JLabel();
        lblErrorNS = new javax.swing.JLabel();
        lblErrorDC = new javax.swing.JLabel();
        lblErrorEmail = new javax.swing.JLabel();
        lblErrorSDT = new javax.swing.JLabel();
        lblErrorGT = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Đăng kí");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Đăng kí tài khoản");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Tên tài khoản: ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Mật khẩu: ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Họ tên: ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Ngày sinh (dd/mm/yyyy): ");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Địa chỉ: ");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Email: ");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Số điện thoại: ");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Giới tính: ");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Nhập lại mật khẩu: ");

        btnDanhKi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDanhKi.setText("Đăng kí");
        btnDanhKi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDanhKiMouseClicked(evt);
            }
        });
        btnDanhKi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDanhKiActionPerformed(evt);
            }
        });

        radNam.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        radNam.setText("Nam");

        radNu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        radNu.setText("Nữ");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Bạn có tài khoản rồi? Đăng nhập ngay: ");

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("Đăng nhập");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblErrorTK.setForeground(new java.awt.Color(255, 0, 51));
        lblErrorTK.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblErrorTK.setText("jLabel12");

        lblErrorMK.setForeground(new java.awt.Color(255, 0, 51));
        lblErrorMK.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblErrorMK.setText("jLabel13");

        lblErrorNLMK.setForeground(new java.awt.Color(255, 0, 51));
        lblErrorNLMK.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblErrorNLMK.setText("jLabel14");

        lblErrorHT.setForeground(new java.awt.Color(255, 0, 51));
        lblErrorHT.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblErrorHT.setText("jLabel15");

        lblErrorNS.setForeground(new java.awt.Color(255, 0, 51));
        lblErrorNS.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblErrorNS.setText("jLabel16");

        lblErrorDC.setForeground(new java.awt.Color(255, 0, 51));
        lblErrorDC.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblErrorDC.setText("jLabel17");

        lblErrorEmail.setForeground(new java.awt.Color(255, 0, 51));
        lblErrorEmail.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblErrorEmail.setText("jLabel18");

        lblErrorSDT.setForeground(new java.awt.Color(255, 0, 51));
        lblErrorSDT.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblErrorSDT.setText("jLabel19");

        lblErrorGT.setForeground(new java.awt.Color(255, 0, 51));
        lblErrorGT.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblErrorGT.setText("jLabel20");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 635, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(btnDanhKi)
                        .addGap(191, 191, 191))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNgay)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtThang)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNam))
                            .addComponent(txtTenTaiKhoan)
                            .addComponent(txtPw)
                            .addComponent(txtNhapLaiPw)
                            .addComponent(txtHoTen)
                            .addComponent(txtDiaChi)
                            .addComponent(txtEmail)
                            .addComponent(txtSoDT)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radNam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(radNu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(94, 94, 94))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblErrorTK, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblErrorMK, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblErrorNLMK, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblErrorHT, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblErrorNS, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblErrorDC, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblErrorEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblErrorSDT, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblErrorGT, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTenTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblErrorTK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtPw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblErrorMK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtNhapLaiPw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblErrorNLMK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblErrorHT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, Short.MAX_VALUE)
                            .addComponent(txtNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblErrorNS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblErrorDC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblErrorEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtSoDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblErrorSDT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radNam)
                            .addComponent(radNu)
                            .addComponent(jLabel9))
                        .addGap(5, 5, 5)
                        .addComponent(lblErrorGT)
                        .addGap(2, 2, 2)
                        .addComponent(btnDanhKi)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jButton1))
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    public boolean checkTK(){
        String name = txtTenTaiKhoan.getText();
        if(name.equals("")){
            lblErrorTK.setText("Tên tài khoản không được bỏ trống. ");
            return false;
        }
        lblErrorTK.setText("");
        return true;
    }
    
    public boolean checkPw() {
        String pw = txtPw.getText(), confirmPw = txtNhapLaiPw.getText();
        // Kiểm tra độ dài
        if (pw.length() < 8 || pw.length() > 32) {
            lblErrorMK.setText("Mật khẩu phải từ 8 đến 32 ký tự. ");
            return false;
        }
        // Kiểm tra khoảng trắng
        if (pw.contains(" ")) {
            lblErrorMK.setText("Mật khẩu không được chứa dấu cách. ");
            return false;
        }
        // Kiểm tra có ít nhất một chữ số
        if (!pw.matches(".*\\d.*")) {
            lblErrorMK.setText("Mật khẩu phải có ít nhất một chữ số. ");
            return false;
        }
        // Kiểm tra có ít nhất một chữ in hoa
        if (!pw.matches(".*[A-Z].*")) {
            lblErrorMK.setText("Mật khẩu phải có ít nhất một chữ in hoa. ");
            return false;
        }
        // Kiểm tra sự giống nhau
        if (!pw.equals(confirmPw)) {
            lblErrorNLMK.setText("Mật khẩu và xác nhận mật khẩu không giống nhau. ");
            return false;
        }
        
        lblErrorNLMK.setText("");
        lblErrorMK.setText("");
        return true;
    }
    
    public boolean checkHT(){
        String name = txtHoTen.getText();
        if(name.equals("")){
            lblErrorHT.setText("Họ tên không được bỏ trống. ");
            return false;
        }
        lblErrorHT.setText("");
        return true;
    }
    
    public boolean checkDC(){
        String name = txtDiaChi.getText();
        if(name.equals("")){
            lblErrorDC.setText("Địa chỉ không được bỏ trống. ");
            return false;
        }
        lblErrorDC.setText("");
        return true;
    }
    public boolean checkDate(){
        try{
            int day = Integer.parseInt(txtNgay.getText());
            int month = Integer.parseInt(txtThang.getText());
            int year = Integer.parseInt(txtNam.getText());
            LocalDate currentDate = LocalDate.now();
            LocalDate ageLimitDate = currentDate.minusYears(13); //lấy ngày hiện tại trừ 13 năm
            boolean isLeapYear = (year % 4 == 0 && year % 100 != 0) || (year % 400 == 0);

            // Số ngày trong các tháng
            int[] daysInMonth = {31, 28 + (isLeapYear ? 1 : 0), 31, 30, 31, 30, 31, 31, 30, 31, 30, 31};

            // Kiểm tra tháng
            if (month < 1 || month > 12) {
                lblErrorNS.setText("Tháng không hợp lệ. ");
                return false;
            }
               
            // Kiểm tra ngày
            if (day < 1 || day > daysInMonth[month - 1]) {
                lblErrorNS.setText("Ngày không hợp lệ. ");
                return false;
            }
                
            // Kiểm tra năm
            if(year < 1900 || year > currentDate.getYear()){
                lblErrorNS.setText("Năm nhập không hợp lệ. ");
                return false;
            }
            
            LocalDate userDate = LocalDate.of(year, month, day); //Tạo đối tượng lưu ngày nhập
            if (userDate.isAfter(ageLimitDate)) {
                lblErrorNS.setText("Người dùng chưa đủ 13 tuổi để đăng ký.");
                return false;
            }
            
            lblErrorNS.setText("");
            return true;
        }catch(Exception e){
            lblErrorNS.setText("Ngày sinh bị bỏ trống hoặc điền sai định dạng. ");
            return false;
        }
    }
    
    public boolean checkEmail(){
        String email = txtEmail.getText();
        if(email.equals("")){
            lblErrorEmail.setText("Email đang bị bỏ trống. ");
            return false;
        }
            
        if (!email.contains("@")){
            lblErrorEmail.setText("Chưa đúng định dạng email. ");
            return false;
        }
        
        lblErrorEmail.setText("");
        return true;
    }
    
    public boolean checkSdt(){
        String sdt = txtSoDT.getText();
        
        if(sdt.equals("")){
            lblErrorSDT.setText("Số điện thoại không được bỏ trống. ");
            return false;
        }
        
        if(sdt.charAt(0) != '0' || sdt.length() != 10 || !sdt.matches("\\d+")){
            lblErrorSDT.setText("Số điện thoại không hợp lệ. ");
            return false;
        }
        
        lblErrorSDT.setText("");
        return true;
    }
    
    public boolean checkGender(){
        if(!radNam.isSelected() && !radNu.isSelected()){
            lblErrorGT.setText("Bạn chưa chọn giới tính. ");
            return false;
        }
        lblErrorGT.setText("");
        return true;
    }
    
    private void btnDanhKiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDanhKiActionPerformed
        boolean error = checkTK() && checkPw() && checkHT() && checkDate() && checkDC() && checkEmail() && checkSdt() && checkGender();
        if(error){
            try {
                String tenTK = txtTenTaiKhoan.getText();
                String matKhau = txtPw.getText();
                String hoTen = txtHoTen.getText();
                int day = Integer.parseInt(txtNgay.getText());
                int month = Integer.parseInt(txtThang.getText());
                int year = Integer.parseInt(txtNam.getText());
                java.time.LocalDate localDate = java.time.LocalDate.of(year, month, day);
                
                String diaChi = txtDiaChi.getText();
                String email = txtEmail.getText();
                String sdt = txtSoDT.getText();
                int gt;
                if(radNam.isSelected())
                    gt = 1;
                else
                    gt = 0;
                //String username, String password, String fullname, LocalDate birthday, int gender, String email, String city, String phone
                User user = new User(tenTK, matKhau, hoTen, localDate, gt, email, diaChi, sdt);
                UserDAO userDAO = new UserDAO();
                boolean result = userDAO.addUser(user);
                if(result){
                    JOptionPane.showMessageDialog(this, "Đăng kí thành công", "Thành công", JOptionPane.INFORMATION_MESSAGE);
                    FrmDangNhap f = new FrmDangNhap();
                    f.setVisible(true);
                    this.dispose();
                }else
                    JOptionPane.showMessageDialog(this, "Đăng kí thất bại", "Thất bại", JOptionPane.INFORMATION_MESSAGE);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(FrmDangKi.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(FrmDangKi.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnDanhKiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmDangNhap().setVisible(true);
            }
        });
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnDanhKiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDanhKiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDanhKiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDangKi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDangKi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDangKi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDangKi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmDangKi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDanhKi;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblErrorDC;
    private javax.swing.JLabel lblErrorEmail;
    private javax.swing.JLabel lblErrorGT;
    private javax.swing.JLabel lblErrorHT;
    private javax.swing.JLabel lblErrorMK;
    private javax.swing.JLabel lblErrorNLMK;
    private javax.swing.JLabel lblErrorNS;
    private javax.swing.JLabel lblErrorSDT;
    private javax.swing.JLabel lblErrorTK;
    private javax.swing.JRadioButton radNam;
    private javax.swing.JRadioButton radNu;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtNam;
    private javax.swing.JTextField txtNgay;
    private javax.swing.JPasswordField txtNhapLaiPw;
    private javax.swing.JPasswordField txtPw;
    private javax.swing.JTextField txtSoDT;
    private javax.swing.JTextField txtTenTaiKhoan;
    private javax.swing.JTextField txtThang;
    // End of variables declaration//GEN-END:variables
}
