/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Models.User;
import Views.PnlUserPhim;
import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;
import javax.swing.JLabel;

/**
 *
 * @author nguye
 */
public class FrmUserMain extends javax.swing.JFrame {
    private User curentUser;
    /**
     * Creates new form FrmUserMain
     * @param user
     */
    public FrmUserMain(User user) {
        initComponents();
        curentUser = user;
        String[] words = user.getFullname().split(" ");
        lblUser.setText(lblUser.getText() + words[words.length - 1]);
        color = btnColor1.getBackground();
        this.setResizable(false);
//        updateLabelState(lblPhim);
//        pnlMain.setLayout(new BorderLayout());
//        setForm(new PnlUserPhim());
        setUser(user);
    }
    public void setUser(User user){
        curentUser = user;
    }
    public FrmUserMain() {
        initComponents();
        System.out.println("Khoi tao kh tham so");
        color = btnColor1.getBackground();
        this.setResizable(false);
//        updateLabelState(lblPhim);
//        pnlMain.setLayout(new BorderLayout());
//        setForm(new PnlUserPhim());
        
    }

    public Color color;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblPhim = new javax.swing.JLabel();
        lblVe = new javax.swing.JLabel();
        btnColor2 = new javax.swing.JButton();
        btnColor3 = new javax.swing.JButton();
        btnColor4 = new javax.swing.JButton();
        btnColor5 = new javax.swing.JButton();
        btnColor1 = new javax.swing.JButton();
        lblCDTK = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        pnlMain = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        lblPhim.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPhim.setForeground(new java.awt.Color(255, 255, 255));
        lblPhim.setText(" Phim chiếu rạp");
        lblPhim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPhimMouseClicked(evt);
            }
        });

        lblVe.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblVe.setForeground(new java.awt.Color(255, 255, 255));
        lblVe.setText(" Vé đã đặt");
        lblVe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblVeMouseEntered(evt);
            }
        });

        btnColor2.setBackground(new java.awt.Color(102, 0, 102));
        btnColor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColor2ActionPerformed(evt);
            }
        });

        btnColor3.setBackground(new java.awt.Color(153, 0, 0));
        btnColor3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColor3ActionPerformed(evt);
            }
        });

        btnColor4.setBackground(new java.awt.Color(102, 102, 0));
        btnColor4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColor4ActionPerformed(evt);
            }
        });

        btnColor5.setBackground(new java.awt.Color(0, 102, 51));
        btnColor5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColor5ActionPerformed(evt);
            }
        });

        btnColor1.setBackground(new java.awt.Color(0, 102, 102));
        btnColor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColor1ActionPerformed(evt);
            }
        });

        lblCDTK.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCDTK.setForeground(new java.awt.Color(255, 255, 255));
        lblCDTK.setText(" Cài đặt tài khoản");
        lblCDTK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCDTKMouseClicked(evt);
            }
        });

        lblUser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setText("Xin chào: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPhim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblVe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnColor1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnColor2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnColor3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnColor4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnColor5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblCDTK))
                        .addGap(0, 16, Short.MAX_VALUE))
                    .addComponent(lblUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblUser)
                .addGap(47, 47, 47)
                .addComponent(lblPhim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblVe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCDTK)
                .addGap(290, 290, 290)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnColor2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnColor3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnColor4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnColor5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnColor1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        pnlMain.setMaximumSize(new java.awt.Dimension(717, 515));
        pnlMain.setMinimumSize(new java.awt.Dimension(621, 476));
        pnlMain.setOpaque(false);
        pnlMain.setPreferredSize(new java.awt.Dimension(717, 515));

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 717, Short.MAX_VALUE)
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 527, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateLabelState(JLabel selectedLabel) {
        // Đặt các nhãn khác thành không hiển thị nền
        lblVe.setOpaque(false);
        lblPhim.setOpaque(false);

        // Đặt nhãn đã chọn thành hiển thị nền
        selectedLabel.setOpaque(true);
        selectedLabel.setBackground(color);

        //Đóng menu con nếu chọn sang lbl khác

        // Cập nhật lại giao diện
        lblVe.repaint();
        lblPhim.repaint();
    }
    
    private void setForm(JComponent c){
        pnlMain.removeAll(); //Xoá toàn bộ các thành phần
        pnlMain.add(c); //Thêm form
        pnlMain.repaint(); //Cập nhật lại giao diện
        pnlMain.revalidate(); //Cập nhật lại bố cục
    }
    
    public void rePaint(){
        lblVe.setBackground(color);
        lblPhim.setBackground(color);
        lblVe.repaint();
        lblPhim.repaint();
    }
    
    private void lblPhimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPhimMouseClicked
        if(curentUser == null){
            System.out.println("Không tìm thấy user ở Main");
        }
        updateLabelState(lblPhim);
        pnlMain.setLayout(new BorderLayout());
        setForm(new PnlUserPhim(curentUser));
        
    }//GEN-LAST:event_lblPhimMouseClicked

    private void lblVeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVeMouseClicked
//        updateLabelState(lblVe);
//        pnlMain.setLayout(new BorderLayout());
//        setForm(new PnlChoNgoi());
        updateLabelState(lblVe);
        pnlMain.setLayout(new BorderLayout());
        setForm(new PnlUsVeDaDat(curentUser));

    }//GEN-LAST:event_lblVeMouseClicked

    private void btnColor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColor2ActionPerformed
        color = btnColor2.getBackground();
        rePaint();
    }//GEN-LAST:event_btnColor2ActionPerformed

    private void btnColor3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColor3ActionPerformed
        color = btnColor3.getBackground();
        rePaint();
    }//GEN-LAST:event_btnColor3ActionPerformed

    private void btnColor4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColor4ActionPerformed
        color = btnColor4.getBackground();
        rePaint();
    }//GEN-LAST:event_btnColor4ActionPerformed

    private void btnColor5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColor5ActionPerformed
        color = btnColor5.getBackground();
        rePaint();
    }//GEN-LAST:event_btnColor5ActionPerformed

    private void btnColor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColor1ActionPerformed
        color = btnColor1.getBackground();
        rePaint();
    }//GEN-LAST:event_btnColor1ActionPerformed

    private void lblVeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVeMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblVeMouseEntered

    private void lblCDTKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCDTKMouseClicked
        // TODO add your handling code here:
        updateLabelState(lblCDTK);
        pnlMain.setLayout(new BorderLayout());
        setForm(new PnlCaiDatTaiKhoan(curentUser));
    }//GEN-LAST:event_lblCDTKMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmUserMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmUserMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmUserMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmUserMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmUserMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnColor1;
    private javax.swing.JButton btnColor2;
    private javax.swing.JButton btnColor3;
    private javax.swing.JButton btnColor4;
    private javax.swing.JButton btnColor5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCDTK;
    private javax.swing.JLabel lblPhim;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lblVe;
    private javax.swing.JPanel pnlMain;
    // End of variables declaration//GEN-END:variables
}
